// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vdzhagaev/watchlight/internal/monitor"
)

// NewMockIncidentRepository creates a new instance of MockIncidentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncidentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncidentRepository {
	mock := &MockIncidentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncidentRepository is an autogenerated mock type for the IncidentRepository type
type MockIncidentRepository struct {
	mock.Mock
}

type MockIncidentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncidentRepository) EXPECT() *MockIncidentRepository_Expecter {
	return &MockIncidentRepository_Expecter{mock: &_m.Mock}
}

// GetOpenByMonitor provides a mock function for the type MockIncidentRepository
func (_mock *MockIncidentRepository) GetOpenByMonitor(ctx context.Context, monitorID uuid.UUID) (monitor.Incident, bool, error) {
	ret := _mock.Called(ctx, monitorID)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenByMonitor")
	}

	var r0 monitor.Incident
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (monitor.Incident, bool, error)); ok {
		return returnFunc(ctx, monitorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) monitor.Incident); ok {
		r0 = returnFunc(ctx, monitorID)
	} else {
		r0 = ret.Get(0).(monitor.Incident)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = returnFunc(ctx, monitorID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, monitorID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIncidentRepository_GetOpenByMonitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenByMonitor'
type MockIncidentRepository_GetOpenByMonitor_Call struct {
	*mock.Call
}

// GetOpenByMonitor is a helper method to define mock.On call
//   - ctx context.Context
//   - monitorID uuid.UUID
func (_e *MockIncidentRepository_Expecter) GetOpenByMonitor(ctx interface{}, monitorID interface{}) *MockIncidentRepository_GetOpenByMonitor_Call {
	return &MockIncidentRepository_GetOpenByMonitor_Call{Call: _e.mock.On("GetOpenByMonitor", ctx, monitorID)}
}

func (_c *MockIncidentRepository_GetOpenByMonitor_Call) Run(run func(ctx context.Context, monitorID uuid.UUID)) *MockIncidentRepository_GetOpenByMonitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncidentRepository_GetOpenByMonitor_Call) Return(incident monitor.Incident, b bool, err error) *MockIncidentRepository_GetOpenByMonitor_Call {
	_c.Call.Return(incident, b, err)
	return _c
}

func (_c *MockIncidentRepository_GetOpenByMonitor_Call) RunAndReturn(run func(ctx context.Context, monitorID uuid.UUID) (monitor.Incident, bool, error)) *MockIncidentRepository_GetOpenByMonitor_Call {
	_c.Call.Return(run)
	return _c
}

// ListMonitorIDsWithOpenIncident provides a mock function for the type MockIncidentRepository
func (_mock *MockIncidentRepository) ListMonitorIDsWithOpenIncident(ctx context.Context) (map[uuid.UUID]struct{}, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListMonitorIDsWithOpenIncident")
	}

	var r0 map[uuid.UUID]struct{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[uuid.UUID]struct{}, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[uuid.UUID]struct{}); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMonitorIDsWithOpenIncident'
type MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call struct {
	*mock.Call
}

// ListMonitorIDsWithOpenIncident is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIncidentRepository_Expecter) ListMonitorIDsWithOpenIncident(ctx interface{}) *MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call {
	return &MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call{Call: _e.mock.On("ListMonitorIDsWithOpenIncident", ctx)}
}

func (_c *MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call) Run(run func(ctx context.Context)) *MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call) Return(uUIDToVal map[uuid.UUID]struct{}, err error) *MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call {
	_c.Call.Return(uUIDToVal, err)
	return _c
}

func (_c *MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call) RunAndReturn(run func(ctx context.Context) (map[uuid.UUID]struct{}, error)) *MockIncidentRepository_ListMonitorIDsWithOpenIncident_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockIncidentRepository
func (_mock *MockIncidentRepository) Save(ctx context.Context, inc monitor.Incident) error {
	ret := _mock.Called(ctx, inc)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, monitor.Incident) error); ok {
		r0 = returnFunc(ctx, inc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncidentRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIncidentRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - inc monitor.Incident
func (_e *MockIncidentRepository_Expecter) Save(ctx interface{}, inc interface{}) *MockIncidentRepository_Save_Call {
	return &MockIncidentRepository_Save_Call{Call: _e.mock.On("Save", ctx, inc)}
}

func (_c *MockIncidentRepository_Save_Call) Run(run func(ctx context.Context, inc monitor.Incident)) *MockIncidentRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 monitor.Incident
		if args[1] != nil {
			arg1 = args[1].(monitor.Incident)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncidentRepository_Save_Call) Return(err error) *MockIncidentRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncidentRepository_Save_Call) RunAndReturn(run func(ctx context.Context, inc monitor.Incident) error) *MockIncidentRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
