// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vdzhagaev/watchlight/internal/monitor"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddHTTPConfig provides a mock function for the type MockRepository
func (_mock *MockRepository) AddHTTPConfig(ctx context.Context, cfg monitor.HTTPConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for AddHTTPConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, monitor.HTTPConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddHTTPConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHTTPConfig'
type MockRepository_AddHTTPConfig_Call struct {
	*mock.Call
}

// AddHTTPConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg monitor.HTTPConfig
func (_e *MockRepository_Expecter) AddHTTPConfig(ctx interface{}, cfg interface{}) *MockRepository_AddHTTPConfig_Call {
	return &MockRepository_AddHTTPConfig_Call{Call: _e.mock.On("AddHTTPConfig", ctx, cfg)}
}

func (_c *MockRepository_AddHTTPConfig_Call) Run(run func(ctx context.Context, cfg monitor.HTTPConfig)) *MockRepository_AddHTTPConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 monitor.HTTPConfig
		if args[1] != nil {
			arg1 = args[1].(monitor.HTTPConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_AddHTTPConfig_Call) Return(err error) *MockRepository_AddHTTPConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddHTTPConfig_Call) RunAndReturn(run func(ctx context.Context, cfg monitor.HTTPConfig) error) *MockRepository_AddHTTPConfig_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMonitor provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateMonitor(ctx context.Context, m monitor.Monitor) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateMonitor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, monitor.Monitor) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateMonitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMonitor'
type MockRepository_CreateMonitor_Call struct {
	*mock.Call
}

// CreateMonitor is a helper method to define mock.On call
//   - ctx context.Context
//   - m monitor.Monitor
func (_e *MockRepository_Expecter) CreateMonitor(ctx interface{}, m interface{}) *MockRepository_CreateMonitor_Call {
	return &MockRepository_CreateMonitor_Call{Call: _e.mock.On("CreateMonitor", ctx, m)}
}

func (_c *MockRepository_CreateMonitor_Call) Run(run func(ctx context.Context, m monitor.Monitor)) *MockRepository_CreateMonitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 monitor.Monitor
		if args[1] != nil {
			arg1 = args[1].(monitor.Monitor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateMonitor_Call) Return(err error) *MockRepository_CreateMonitor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateMonitor_Call) RunAndReturn(run func(ctx context.Context, m monitor.Monitor) error) *MockRepository_CreateMonitor_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMonitor provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteMonitor(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMonitor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteMonitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMonitor'
type MockRepository_DeleteMonitor_Call struct {
	*mock.Call
}

// DeleteMonitor is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) DeleteMonitor(ctx interface{}, id interface{}) *MockRepository_DeleteMonitor_Call {
	return &MockRepository_DeleteMonitor_Call{Call: _e.mock.On("DeleteMonitor", ctx, id)}
}

func (_c *MockRepository_DeleteMonitor_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_DeleteMonitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteMonitor_Call) Return(err error) *MockRepository_DeleteMonitor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteMonitor_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRepository_DeleteMonitor_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonitor provides a mock function for the type MockRepository
func (_mock *MockRepository) GetMonitor(ctx context.Context, id uuid.UUID) (monitor.Monitor, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMonitor")
	}

	var r0 monitor.Monitor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (monitor.Monitor, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) monitor.Monitor); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(monitor.Monitor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetMonitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonitor'
type MockRepository_GetMonitor_Call struct {
	*mock.Call
}

// GetMonitor is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetMonitor(ctx interface{}, id interface{}) *MockRepository_GetMonitor_Call {
	return &MockRepository_GetMonitor_Call{Call: _e.mock.On("GetMonitor", ctx, id)}
}

func (_c *MockRepository_GetMonitor_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetMonitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetMonitor_Call) Return(monitor1 monitor.Monitor, err error) *MockRepository_GetMonitor_Call {
	_c.Call.Return(monitor1, err)
	return _c
}

func (_c *MockRepository_GetMonitor_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (monitor.Monitor, error)) *MockRepository_GetMonitor_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonitorList provides a mock function for the type MockRepository
func (_mock *MockRepository) GetMonitorList(ctx context.Context) ([]monitor.Monitor, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMonitorList")
	}

	var r0 []monitor.Monitor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]monitor.Monitor, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []monitor.Monitor); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]monitor.Monitor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetMonitorList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonitorList'
type MockRepository_GetMonitorList_Call struct {
	*mock.Call
}

// GetMonitorList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetMonitorList(ctx interface{}) *MockRepository_GetMonitorList_Call {
	return &MockRepository_GetMonitorList_Call{Call: _e.mock.On("GetMonitorList", ctx)}
}

func (_c *MockRepository_GetMonitorList_Call) Run(run func(ctx context.Context)) *MockRepository_GetMonitorList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetMonitorList_Call) Return(monitors []monitor.Monitor, err error) *MockRepository_GetMonitorList_Call {
	_c.Call.Return(monitors, err)
	return _c
}

func (_c *MockRepository_GetMonitorList_Call) RunAndReturn(run func(ctx context.Context) ([]monitor.Monitor, error)) *MockRepository_GetMonitorList_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveHTTPConfig provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveHTTPConfig(ctx context.Context, configID uuid.UUID) error {
	ret := _mock.Called(ctx, configID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveHTTPConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, configID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveHTTPConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveHTTPConfig'
type MockRepository_RemoveHTTPConfig_Call struct {
	*mock.Call
}

// RemoveHTTPConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - configID uuid.UUID
func (_e *MockRepository_Expecter) RemoveHTTPConfig(ctx interface{}, configID interface{}) *MockRepository_RemoveHTTPConfig_Call {
	return &MockRepository_RemoveHTTPConfig_Call{Call: _e.mock.On("RemoveHTTPConfig", ctx, configID)}
}

func (_c *MockRepository_RemoveHTTPConfig_Call) Run(run func(ctx context.Context, configID uuid.UUID)) *MockRepository_RemoveHTTPConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveHTTPConfig_Call) Return(err error) *MockRepository_RemoveHTTPConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveHTTPConfig_Call) RunAndReturn(run func(ctx context.Context, configID uuid.UUID) error) *MockRepository_RemoveHTTPConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCheckResult provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveCheckResult(ctx context.Context, r monitor.CheckResult) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for SaveCheckResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, monitor.CheckResult) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveCheckResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCheckResult'
type MockRepository_SaveCheckResult_Call struct {
	*mock.Call
}

// SaveCheckResult is a helper method to define mock.On call
//   - ctx context.Context
//   - r monitor.CheckResult
func (_e *MockRepository_Expecter) SaveCheckResult(ctx interface{}, r interface{}) *MockRepository_SaveCheckResult_Call {
	return &MockRepository_SaveCheckResult_Call{Call: _e.mock.On("SaveCheckResult", ctx, r)}
}

func (_c *MockRepository_SaveCheckResult_Call) Run(run func(ctx context.Context, r monitor.CheckResult)) *MockRepository_SaveCheckResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 monitor.CheckResult
		if args[1] != nil {
			arg1 = args[1].(monitor.CheckResult)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveCheckResult_Call) Return(err error) *MockRepository_SaveCheckResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveCheckResult_Call) RunAndReturn(run func(ctx context.Context, r monitor.CheckResult) error) *MockRepository_SaveCheckResult_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHTTPConfig provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateHTTPConfig(ctx context.Context, cfg monitor.HTTPConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHTTPConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, monitor.HTTPConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateHTTPConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHTTPConfig'
type MockRepository_UpdateHTTPConfig_Call struct {
	*mock.Call
}

// UpdateHTTPConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg monitor.HTTPConfig
func (_e *MockRepository_Expecter) UpdateHTTPConfig(ctx interface{}, cfg interface{}) *MockRepository_UpdateHTTPConfig_Call {
	return &MockRepository_UpdateHTTPConfig_Call{Call: _e.mock.On("UpdateHTTPConfig", ctx, cfg)}
}

func (_c *MockRepository_UpdateHTTPConfig_Call) Run(run func(ctx context.Context, cfg monitor.HTTPConfig)) *MockRepository_UpdateHTTPConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 monitor.HTTPConfig
		if args[1] != nil {
			arg1 = args[1].(monitor.HTTPConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateHTTPConfig_Call) Return(err error) *MockRepository_UpdateHTTPConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateHTTPConfig_Call) RunAndReturn(run func(ctx context.Context, cfg monitor.HTTPConfig) error) *MockRepository_UpdateHTTPConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMonitor provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateMonitor(ctx context.Context, id uuid.UUID, in monitor.UpdateMonitorInput) error {
	ret := _mock.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMonitor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, monitor.UpdateMonitorInput) error); ok {
		r0 = returnFunc(ctx, id, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateMonitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMonitor'
type MockRepository_UpdateMonitor_Call struct {
	*mock.Call
}

// UpdateMonitor is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - in monitor.UpdateMonitorInput
func (_e *MockRepository_Expecter) UpdateMonitor(ctx interface{}, id interface{}, in interface{}) *MockRepository_UpdateMonitor_Call {
	return &MockRepository_UpdateMonitor_Call{Call: _e.mock.On("UpdateMonitor", ctx, id, in)}
}

func (_c *MockRepository_UpdateMonitor_Call) Run(run func(ctx context.Context, id uuid.UUID, in monitor.UpdateMonitorInput)) *MockRepository_UpdateMonitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 monitor.UpdateMonitorInput
		if args[2] != nil {
			arg2 = args[2].(monitor.UpdateMonitorInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateMonitor_Call) Return(err error) *MockRepository_UpdateMonitor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateMonitor_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, in monitor.UpdateMonitorInput) error) *MockRepository_UpdateMonitor_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePingConfig provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdatePingConfig(ctx context.Context, cfg monitor.PingConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePingConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, monitor.PingConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdatePingConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePingConfig'
type MockRepository_UpdatePingConfig_Call struct {
	*mock.Call
}

// UpdatePingConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg monitor.PingConfig
func (_e *MockRepository_Expecter) UpdatePingConfig(ctx interface{}, cfg interface{}) *MockRepository_UpdatePingConfig_Call {
	return &MockRepository_UpdatePingConfig_Call{Call: _e.mock.On("UpdatePingConfig", ctx, cfg)}
}

func (_c *MockRepository_UpdatePingConfig_Call) Run(run func(ctx context.Context, cfg monitor.PingConfig)) *MockRepository_UpdatePingConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 monitor.PingConfig
		if args[1] != nil {
			arg1 = args[1].(monitor.PingConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdatePingConfig_Call) Return(err error) *MockRepository_UpdatePingConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdatePingConfig_Call) RunAndReturn(run func(ctx context.Context, cfg monitor.PingConfig) error) *MockRepository_UpdatePingConfig_Call {
	_c.Call.Return(run)
	return _c
}
